/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author Gerardo Rico
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        iniciarSesion = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        usr = new javax.swing.JTextField();
        pwd = new javax.swing.JPasswordField();
        lbl_usuario = new javax.swing.JLabel();
        lbl_pwd = new javax.swing.JLabel();
        bienvenido = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(247, 247, 247));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciarSesion.setBackground(new java.awt.Color(51, 153, 0));
        iniciarSesion.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        iniciarSesion.setText("Iniciar Sesion");
        iniciarSesion.setFocusPainted(false);
        iniciarSesion.setFocusable(false);
        iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionActionPerformed(evt);
            }
        });
        panel.add(iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 190, -1));

        salir.setBackground(new java.awt.Color(255, 51, 51));
        salir.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.setFocusPainted(false);
        salir.setFocusable(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        panel.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        usr.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        panel.add(usr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 130, -1));

        pwd.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        panel.add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 130, -1));

        lbl_usuario.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        lbl_usuario.setText("Usuario:");
        panel.add(lbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        lbl_pwd.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        lbl_pwd.setText("Contraseña:");
        panel.add(lbl_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        bienvenido.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        bienvenido.setText("Bienvenido(a)");
        panel.add(bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        mensaje.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        mensaje.setForeground(new java.awt.Color(255, 0, 51));
        mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 260, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_puntov_60x60.png"))); // NOI18N
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 380, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-login_2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 150, 150));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes-gratis-mandala-wallpaper-hd-fotos-fondos-pantalla-buda (38).png"))); // NOI18N
        fondo.setFocusable(false);
        fondo.setOpaque(true);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 410, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed

        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionActionPerformed
        
        boolean valida_ingreso = false;
        
        if(valida_ingreso)
        {
            JOptionPane.showMessageDialog(null, "Bienvenido!");
        }
        else
        {
            usr.setText("");
            pwd.setText("");
            mensaje.setText("Oops... Vuelve a intentar!");
            usr.transferFocus();
        }
        
    }//GEN-LAST:event_iniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenido;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton iniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_pwd;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JLabel mensaje;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JButton salir;
    private javax.swing.JTextField usr;
    // End of variables declaration//GEN-END:variables
}
